version: '3'
services:
  api:
    build: ./node
    container_name: 'api'
    tty: true
    volumes:
      - ./api:/home/app
    ports:
      - '5080:5080'
  nginx:
    image: nginx
    container_name: 'nginx'
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
